# Generated by Django 5.2 on 2025-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0002_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.png', null=True, upload_to='media/avatars/'),
        ),
    ]
