# Generated by Django 5.2 on 2025-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/deafualt_avatar/default.png', null=True, upload_to='media/avatars/'),
        ),
    ]
